/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfPacedLearningRouteImport } from './routes/self-paced-learning'
import { Route as ResearchSupportRouteImport } from './routes/research-support'
import { Route as ItSolutionsRouteImport } from './routes/it-solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultancyRouteImport } from './routes/consultancy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SelfPacedLearningRoute = SelfPacedLearningRouteImport.update({
  id: '/self-paced-learning',
  path: '/self-paced-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSupportRoute = ResearchSupportRouteImport.update({
  id: '/research-support',
  path: '/research-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ItSolutionsRoute = ItSolutionsRouteImport.update({
  id: '/it-solutions',
  path: '/it-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyRoute = ConsultancyRouteImport.update({
  id: '/consultancy',
  path: '/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/it-solutions': typeof ItSolutionsRoute
  '/research-support': typeof ResearchSupportRoute
  '/self-paced-learning': typeof SelfPacedLearningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/it-solutions': typeof ItSolutionsRoute
  '/research-support': typeof ResearchSupportRoute
  '/self-paced-learning': typeof SelfPacedLearningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultancy': typeof ConsultancyRoute
  '/contact': typeof ContactRoute
  '/it-solutions': typeof ItSolutionsRoute
  '/research-support': typeof ResearchSupportRoute
  '/self-paced-learning': typeof SelfPacedLearningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/it-solutions'
    | '/research-support'
    | '/self-paced-learning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/it-solutions'
    | '/research-support'
    | '/self-paced-learning'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultancy'
    | '/contact'
    | '/it-solutions'
    | '/research-support'
    | '/self-paced-learning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultancyRoute: typeof ConsultancyRoute
  ContactRoute: typeof ContactRoute
  ItSolutionsRoute: typeof ItSolutionsRoute
  ResearchSupportRoute: typeof ResearchSupportRoute
  SelfPacedLearningRoute: typeof SelfPacedLearningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-paced-learning': {
      id: '/self-paced-learning'
      path: '/self-paced-learning'
      fullPath: '/self-paced-learning'
      preLoaderRoute: typeof SelfPacedLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-support': {
      id: '/research-support'
      path: '/research-support'
      fullPath: '/research-support'
      preLoaderRoute: typeof ResearchSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-solutions': {
      id: '/it-solutions'
      path: '/it-solutions'
      fullPath: '/it-solutions'
      preLoaderRoute: typeof ItSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy': {
      id: '/consultancy'
      path: '/consultancy'
      fullPath: '/consultancy'
      preLoaderRoute: typeof ConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultancyRoute: ConsultancyRoute,
  ContactRoute: ContactRoute,
  ItSolutionsRoute: ItSolutionsRoute,
  ResearchSupportRoute: ResearchSupportRoute,
  SelfPacedLearningRoute: SelfPacedLearningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
